name: bookit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_ui_auth: ^1.13.0
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Bookit.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
